CREATE TABLE profiles (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR(150) NOT NULL,
    email         VARCHAR(150) NOT NULL UNIQUE,
    phone_number  VARCHAR(20)  NOT NULL,
    national_id   VARCHAR(32) UNIQUE,
    address       VARCHAR(255),
    status        VARCHAR(20)  NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_profiles_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) NOT NULL UNIQUE,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_roles_name CHECK (name IN ('ROLE_ADMIN', 'ROLE_OPERATOR', 'ROLE_FINANCE', 'ROLE_CUSTOMER'))
);

CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id  BIGINT      NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_users_profile FOREIGN KEY (profile_id) REFERENCES profiles (id)
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE customers (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id  BIGINT    NOT NULL UNIQUE,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_customers_profile FOREIGN KEY (profile_id) REFERENCES profiles (id)
);

CREATE TABLE meters (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id        BIGINT      NOT NULL,
    meter_number       VARCHAR(50) NOT NULL UNIQUE,
    meter_type         VARCHAR(20) NOT NULL,
    billing_mode       VARCHAR(20) NOT NULL,
    installation_date  DATE        NOT NULL,
    status             VARCHAR(20) NOT NULL,
    created_at         TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_meters_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT chk_meters_type CHECK (meter_type IN ('WATER', 'ELECTRICITY')),
    CONSTRAINT chk_meters_billing_mode CHECK (billing_mode IN ('PREPAID', 'POSTPAID')),
    CONSTRAINT chk_meters_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT chk_water_postpaid CHECK (NOT (meter_type = 'WATER' AND billing_mode = 'PREPAID'))
);

CREATE TABLE meter_readings (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meter_id          BIGINT         NOT NULL,
    previous_reading  NUMERIC(14, 2) NOT NULL,
    current_reading   NUMERIC(14, 2) NOT NULL,
    reading_date      DATE           NOT NULL,
    reading_year      INTEGER        NOT NULL,
    reading_month     INTEGER        NOT NULL,
    created_at        TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_meter_readings_meter FOREIGN KEY (meter_id) REFERENCES meters (id),
    CONSTRAINT uq_meter_reading_period UNIQUE (meter_id, reading_year, reading_month),
    CONSTRAINT chk_meter_readings_values CHECK (current_reading > previous_reading),
    CONSTRAINT chk_meter_readings_month CHECK (reading_month BETWEEN 1 AND 12)
);

CREATE TABLE tariff_versions (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meter_type                 VARCHAR(20)   NOT NULL,
    tariff_type                VARCHAR(20)   NOT NULL,
    version_number             INTEGER       NOT NULL,
    effective_from             DATE          NOT NULL,
    fixed_service_charge       NUMERIC(14, 2) NOT NULL,
    vat_rate                   NUMERIC(5, 4)  NOT NULL,
    late_payment_penalty_rate  NUMERIC(5, 4)  NOT NULL,
    created_at                 TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                 TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_tariff_versions UNIQUE (meter_type, effective_from, version_number),
    CONSTRAINT chk_tariff_meter_type CHECK (meter_type IN ('WATER', 'ELECTRICITY')),
    CONSTRAINT chk_tariff_type CHECK (tariff_type IN ('FLAT', 'TIERED')),
    CONSTRAINT chk_tariff_vat CHECK (vat_rate = 0.1800),
    CONSTRAINT chk_tariff_penalty CHECK (late_payment_penalty_rate >= 0)
);

CREATE TABLE tariff_tiers (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tariff_version_id  BIGINT          NOT NULL,
    from_unit          INTEGER         NOT NULL,
    to_unit            INTEGER,
    price_per_unit     NUMERIC(14, 2)  NOT NULL,
    created_at         TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tariff_tiers_version FOREIGN KEY (tariff_version_id) REFERENCES tariff_versions (id),
    CONSTRAINT chk_tariff_tiers_bounds CHECK (to_unit IS NULL OR to_unit > from_unit)
);

CREATE TABLE bills (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_reference       VARCHAR(80)   NOT NULL UNIQUE,
    customer_id          BIGINT        NOT NULL,
    meter_id             BIGINT        NOT NULL,
    reading_id           BIGINT        NOT NULL UNIQUE,
    tariff_version_id    BIGINT        NOT NULL,
    billing_year         INTEGER       NOT NULL,
    billing_month        INTEGER       NOT NULL,
    due_date             DATE          NOT NULL,
    consumption_units    NUMERIC(14, 2) NOT NULL,
    subtotal             NUMERIC(14, 2) NOT NULL,
    vat_amount           NUMERIC(14, 2) NOT NULL,
    penalty_amount       NUMERIC(14, 2) NOT NULL,
    total_amount         NUMERIC(14, 2) NOT NULL,
    amount_paid          NUMERIC(14, 2) NOT NULL,
    outstanding_balance  NUMERIC(14, 2) NOT NULL,
    status               VARCHAR(30)   NOT NULL,
    generated_by         BIGINT,
    approved_by          BIGINT,
    approved_at          TIMESTAMP,
    created_at           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bills_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT fk_bills_meter FOREIGN KEY (meter_id) REFERENCES meters (id),
    CONSTRAINT fk_bills_reading FOREIGN KEY (reading_id) REFERENCES meter_readings (id),
    CONSTRAINT fk_bills_tariff FOREIGN KEY (tariff_version_id) REFERENCES tariff_versions (id),
    CONSTRAINT fk_bills_generated_by FOREIGN KEY (generated_by) REFERENCES users (id),
    CONSTRAINT fk_bills_approved_by FOREIGN KEY (approved_by) REFERENCES users (id),
    CONSTRAINT chk_bills_status CHECK (status IN ('PENDING_APPROVAL', 'APPROVED', 'PARTIALLY_PAID', 'PAID')),
    CONSTRAINT chk_bills_month CHECK (billing_month BETWEEN 1 AND 12),
    CONSTRAINT chk_bills_amounts CHECK (
        subtotal >= 0 AND vat_amount >= 0 AND penalty_amount >= 0
        AND total_amount >= 0 AND amount_paid >= 0 AND outstanding_balance >= 0
    )
);

CREATE TABLE bill_line_items (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id        BIGINT          NOT NULL,
    line_type      VARCHAR(30)     NOT NULL,
    description    VARCHAR(150)    NOT NULL,
    quantity       NUMERIC(14, 2)  NOT NULL,
    unit_price     NUMERIC(14, 2)  NOT NULL,
    amount         NUMERIC(14, 2)  NOT NULL,
    display_order  INTEGER         NOT NULL,
    created_at     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bill_line_items_bill FOREIGN KEY (bill_id) REFERENCES bills (id),
    CONSTRAINT chk_bill_line_items_type CHECK (line_type IN ('CONSUMPTION', 'SERVICE_CHARGE', 'VAT', 'LATE_PENALTY'))
);

CREATE TABLE payments (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_reference  VARCHAR(80)   NOT NULL UNIQUE,
    bill_id            BIGINT        NOT NULL,
    amount_paid        NUMERIC(14, 2) NOT NULL,
    payment_method     VARCHAR(30)   NOT NULL,
    payment_date       DATE          NOT NULL,
    status             VARCHAR(30)   NOT NULL,
    recorded_by        BIGINT,
    approved_by        BIGINT,
    approved_at        TIMESTAMP,
    created_at         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payments_bill FOREIGN KEY (bill_id) REFERENCES bills (id),
    CONSTRAINT fk_payments_recorded_by FOREIGN KEY (recorded_by) REFERENCES users (id),
    CONSTRAINT fk_payments_approved_by FOREIGN KEY (approved_by) REFERENCES users (id),
    CONSTRAINT chk_payments_method CHECK (payment_method IN ('CASH', 'BANK_TRANSFER', 'MOMO', 'VISA')),
    CONSTRAINT chk_payments_status CHECK (status IN ('PENDING_APPROVAL', 'APPROVED', 'REJECTED')),
    CONSTRAINT chk_payments_amount CHECK (amount_paid > 0)
);

CREATE TABLE notifications (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id        BIGINT       NOT NULL,
    bill_id            BIGINT,
    payment_id         BIGINT,
    notification_type  VARCHAR(40)  NOT NULL,
    message            VARCHAR(500) NOT NULL,
    status             VARCHAR(20)  NOT NULL,
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifications_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT fk_notifications_bill FOREIGN KEY (bill_id) REFERENCES bills (id),
    CONSTRAINT fk_notifications_payment FOREIGN KEY (payment_id) REFERENCES payments (id),
    CONSTRAINT chk_notifications_type CHECK (notification_type IN ('BILL_GENERATED', 'PAYMENT_COMPLETED')),
    CONSTRAINT chk_notifications_status CHECK (status IN ('PENDING', 'SENT'))
);

INSERT INTO roles (name) VALUES
    ('ROLE_ADMIN'),
    ('ROLE_OPERATOR'),
    ('ROLE_FINANCE'),
    ('ROLE_CUSTOMER');

CREATE INDEX idx_users_profile_id ON users (profile_id);
CREATE INDEX idx_customers_profile_id ON customers (profile_id);
CREATE INDEX idx_meters_customer_id ON meters (customer_id);
CREATE INDEX idx_meter_readings_meter_id ON meter_readings (meter_id);
CREATE INDEX idx_tariff_versions_lookup ON tariff_versions (meter_type, effective_from DESC, version_number DESC);
CREATE INDEX idx_bills_customer_id ON bills (customer_id);
CREATE INDEX idx_bills_status ON bills (status);
CREATE INDEX idx_payments_bill_id ON payments (bill_id);
CREATE INDEX idx_payments_status ON payments (status);
CREATE INDEX idx_notifications_customer_id ON notifications (customer_id);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION insert_bill_notification()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    customer_name TEXT;
    bill_period TEXT;
BEGIN
    SELECT p.full_name
      INTO customer_name
      FROM customers c
      JOIN profiles p ON p.id = c.profile_id
     WHERE c.id = NEW.customer_id;

    bill_period := to_char(make_date(NEW.billing_year, NEW.billing_month, 1), 'FMMonth') || ' / ' || NEW.billing_year;

    INSERT INTO notifications (customer_id, bill_id, notification_type, message, status)
    VALUES (
        NEW.customer_id,
        NEW.id,
        'BILL_GENERATED',
        'Dear ' || customer_name || E'.\nYour ' || bill_period || ' utility bill of ' || NEW.total_amount || ' FRW has been successfully processed.',
        'PENDING'
    );
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION apply_payment_approval()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    approved_total NUMERIC(14, 2);
    bill_total NUMERIC(14, 2);
    bill_year INTEGER;
    bill_month INTEGER;
    customer_id_ref BIGINT;
    customer_name TEXT;
    bill_period TEXT;
BEGIN
    IF NEW.status <> 'APPROVED' OR (TG_OP = 'UPDATE' AND OLD.status = 'APPROVED') THEN
        RETURN NEW;
    END IF;

    SELECT COALESCE(SUM(amount_paid), 0.00)
      INTO approved_total
      FROM payments
     WHERE bill_id = NEW.bill_id
       AND status = 'APPROVED';

    SELECT total_amount, billing_year, billing_month, customer_id
      INTO bill_total, bill_year, bill_month, customer_id_ref
      FROM bills
     WHERE id = NEW.bill_id;

    UPDATE bills
       SET amount_paid = approved_total,
           outstanding_balance = GREATEST(total_amount - approved_total, 0.00),
           status = CASE
               WHEN approved_total >= total_amount THEN 'PAID'
               WHEN approved_total > 0 THEN 'PARTIALLY_PAID'
               ELSE status
           END
     WHERE id = NEW.bill_id;

    IF approved_total >= bill_total THEN
        SELECT p.full_name
          INTO customer_name
          FROM customers c
          JOIN profiles p ON p.id = c.profile_id
         WHERE c.id = customer_id_ref;

        bill_period := to_char(make_date(bill_year, bill_month, 1), 'FMMonth') || ' / ' || bill_year;

        INSERT INTO notifications (customer_id, bill_id, payment_id, notification_type, message, status)
        VALUES (
            customer_id_ref,
            NEW.bill_id,
            NEW.id,
            'PAYMENT_COMPLETED',
            'Dear ' || customer_name || E'.\nYour ' || bill_period || ' utility bill of ' || bill_total || ' FRW has been successfully processed.',
            'PENDING'
        );
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_profiles_updated_at
BEFORE UPDATE ON profiles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_roles_updated_at
BEFORE UPDATE ON roles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_customers_updated_at
BEFORE UPDATE ON customers
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_meters_updated_at
BEFORE UPDATE ON meters
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_meter_readings_updated_at
BEFORE UPDATE ON meter_readings
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_tariff_versions_updated_at
BEFORE UPDATE ON tariff_versions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_tariff_tiers_updated_at
BEFORE UPDATE ON tariff_tiers
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_bills_updated_at
BEFORE UPDATE ON bills
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_bill_line_items_updated_at
BEFORE UPDATE ON bill_line_items
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_payments_updated_at
BEFORE UPDATE ON payments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_notifications_updated_at
BEFORE UPDATE ON notifications
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_bill_notification
AFTER INSERT ON bills
FOR EACH ROW EXECUTE FUNCTION insert_bill_notification();

CREATE TRIGGER trg_payment_approval
AFTER INSERT OR UPDATE OF status ON payments
FOR EACH ROW EXECUTE FUNCTION apply_payment_approval();
